"""
Django settings for pipou_blog project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
from pathlib import Path
from urllib.parse import urlparse, parse_qsl
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Ajouter le répertoire parent au Python path pour que Django trouve les apps
sys.path.insert(0, str(BASE_DIR))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-*l!46iy#n(eoz0pu(&+7p29)&$-ktztyzw&u4u64sc-fscd7lw')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['*']  # Vercel will handle the domain routing


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'blog',
    'authentication',
    'user_profile',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Pour servir les fichiers statiques
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pipou_blog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR.joinpath('templates'),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pipou_blog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Configuration pour la base de données
DATABASE_URL = os.getenv("DATABASE_URL")

if DATABASE_URL:
    try:
        tmpPostgres = urlparse(DATABASE_URL)
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': tmpPostgres.path.replace('/', ''),
                'USER': tmpPostgres.username,
                'PASSWORD': tmpPostgres.password,
                'HOST': tmpPostgres.hostname,
                'PORT': tmpPostgres.port or 5432,
                'OPTIONS': dict(parse_qsl(tmpPostgres.query)),
            }
        }
    except Exception as e:
        print(f"Erreur de configuration DATABASE_URL: {e}")
        # Fallback en cas d'erreur de parsing
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.postgresql',
                'NAME': os.getenv('DB_NAME', 'pipou_blog'),
                'USER': os.getenv('DB_USER', 'postgres'),
                'PASSWORD': os.getenv('DB_PASSWORD', ''),
                'HOST': os.getenv('DB_HOST', 'localhost'),
                'PORT': os.getenv('DB_PORT', '5432'),
            }
        }
else:
    # Configuration par défaut pour PostgreSQL (nécessaire pour Vercel)
    # En production, DATABASE_URL doit toujours être défini
    print("ATTENTION: DATABASE_URL n'est pas défini!")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'pipou_blog'),
            'USER': os.getenv('DB_USER', 'postgres'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# En développement local
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
else:
    # En production sur Vercel
    STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles_build', 'static')
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]

# Configuration WhiteNoise pour servir les fichiers statiques
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Configuration du modèle utilisateur personnalisé
AUTH_USER_MODEL = 'authentication.User'

# Configuration des backends d'authentification pour permettre la connexion par email
AUTHENTICATION_BACKENDS = [
    'authentication.backends.EmailBackend',  # Notre backend personnalisé
    'django.contrib.auth.backends.ModelBackend',  # Backend par défaut (fallback)
]

# Configuration des redirections d'authentification
LOGIN_REDIRECT_URL = '/'  # Redirection après connexion réussie
LOGIN_URL = '/authentication/login/'  # URL de la page de connexion
LOGOUT_REDIRECT_URL = '/authentication/login/'  # Redirection après déconnexion

# Pour gérer les fichiers média (images)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Configuration pour Vercel - éviter les redirections infinies
if not DEBUG:
    # Configuration pour HTTPS sur Vercel
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = False  # Vercel gère déjà HTTPS
    USE_TZ = True
    
    # Configuration pour les sessions et cookies - DÉSACTIVÉE pour tester
    SESSION_COOKIE_SECURE = False  # Temporairement désactivé
    CSRF_COOKIE_SECURE = False     # Temporairement désactivé
    
    # SOLUTION POUR ADMIN DJANGO : Désactiver les redirections automatiques ADMIN seulement
    # Mais garder LOGIN_REDIRECT_URL pour que la connexion normale fonctionne
    LOGIN_URL = '/authentication/login/'  # Garder pour la connexion normale
    LOGIN_REDIRECT_URL = '/'  # Rediriger vers l'accueil après connexion
    LOGOUT_REDIRECT_URL = '/authentication/login/'  # Rediriger vers login après déconnexion
    
    # Headers de sécurité - TOUS DÉSACTIVÉS pour tester
    SECURE_BROWSER_XSS_FILTER = False
    SECURE_CONTENT_TYPE_NOSNIFF = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    SECURE_REFERRER_POLICY = None
    
    # Configuration des domaines autorisés
    ALLOWED_HOSTS = ['*']
    
    # Configuration pour éviter les problèmes de reverse proxy
    USE_X_FORWARDED_HOST = True
    USE_X_FORWARDED_PORT = True
    
    # Désactiver complètement les redirections de sécurité
    SECURE_REDIRECT_EXEMPT = [r'^admin/.*']  # Exempter l'admin des redirections
    
    # Configuration spéciale pour éviter les boucles de redirection
    APPEND_SLASH = False  # Désactiver l'ajout automatique de slash
else:
    # Configuration pour le développement local
    LOGIN_URL = '/authentication/login/'
    LOGIN_REDIRECT_URL = '/'
    LOGOUT_REDIRECT_URL = '/authentication/login/'